version: '3.8'

services:
  app:
    build: ./app
    image: compose_demo_app  # הוספת השורה הזו כדי שג'נקינס ידע איזה אימג' לתייג
    container_name: compose_app_container
    environment:
      - USER_NAME=Avital
      - APP_ENV=Development

  tests:
    build: ./tests
    container_name: compose_test_container # שם הקונטיינר שיוצג במערכת
    depends_on:
      - app
    environment:
      - USER_NAME=Avital
      - APP_ENV=Testing